import type { ParsedBinary, ConversionOptions } from '../types';
import { MemoryBuffer } from '../MemoryBuffer';

export function parseCArray(text: string, baseAddress = 0, fileName?: string): ParsedBinary {
  const braceMatch = text.match(/\{([\s\S]*?)\}/);
  const targetText = braceMatch ? braceMatch[1] : text;

  const matches = targetText.match(/0x[0-9a-fA-F]{1,8}|\b[0-9a-fA-F]{2,8}\b/g) || [];
  const bytes: number[] = [];

  for (const m of matches) {
    const rawStr = m.startsWith('0x') || m.startsWith('0X') ? m.substring(2) : m;
    const val = parseInt(rawStr, 16);
    if (!isNaN(val)) {
      if (rawStr.length <= 2) {
        bytes.push(val & 0xff);
      } else if (rawStr.length <= 4) {
        // 16-bit word
        bytes.push((val >> 8) & 0xff);
        bytes.push(val & 0xff);
      } else {
        // 32-bit word
        bytes.push((val >> 24) & 0xff);
        bytes.push((val >> 16) & 0xff);
        bytes.push((val >> 8) & 0xff);
        bytes.push(val & 0xff);
      }
    }
  }

  const segments = [
    {
      startAddress: baseAddress,
      data: new Uint8Array(bytes),
    },
  ];

  const memoryBuffer = new MemoryBuffer(segments);

  return {
    format: 'c_array',
    fileName,
    segments: memoryBuffer.getSegments(),
    minAddress: memoryBuffer.getMinAddress(),
    maxAddress: memoryBuffer.getMaxAddress(),
    totalBytes: memoryBuffer.getTotalBytes(),
    warnings: bytes.length === 0 ? ['No C array byte definitions found inside braces.'] : [],
    errors: [],
  };
}

export function writeCArray(
  memoryBuffer: MemoryBuffer,
  options: ConversionOptions = {}
): string {
  const { buffer, baseAddress } = memoryBuffer.toContiguousBuffer(options);
  const totalLen = buffer.length;
  const arrayName = options.cArrayName || 'firmware_data';
  const cType = options.cType || 'uint8_t';
  const bytesPerLine = options.bytesPerLine ?? 12;
  const isUpper = (options.hexCase || 'upper') === 'upper';

  let elementSize = 1;
  let typeCastName = 'uint8_t';
  if (cType === 'uint16_t') {
    elementSize = 2;
    typeCastName = 'uint16_t';
  } else if (cType === 'uint32_t') {
    elementSize = 4;
    typeCastName = 'uint32_t';
  }

  const elementCount = Math.ceil(totalLen / elementSize);

  const header = `// Generated by OmniHex Binary Converter
// Size: ${totalLen} bytes (${(totalLen / 1024).toFixed(2)} KB), Elements: ${elementCount}
// Base Address: 0x${baseAddress.toString(16).padStart(8, '0').toUpperCase()}

#include <stdint.h>

const ${typeCastName} ${arrayName}[${elementCount}] = {
`;

  const lines: string[] = [];
  const elementsPerLine = Math.max(1, Math.floor(bytesPerLine / elementSize));

  for (let i = 0; i < totalLen; i += elementsPerLine * elementSize) {
    const rowElements: string[] = [];

    for (let e = 0; e < elementsPerLine; e++) {
      const idx = i + e * elementSize;
      if (idx >= totalLen) break;

      let val = 0;
      if (elementSize === 1) {
        val = buffer[idx];
      } else if (elementSize === 2) {
        val = (buffer[idx] << 8) | (buffer[idx + 1] || 0);
      } else if (elementSize === 4) {
        val =
          ((buffer[idx] << 24) |
            ((buffer[idx + 1] || 0) << 16) |
            ((buffer[idx + 2] || 0) << 8) |
            (buffer[idx + 3] || 0)) >>>
          0;
      }

      const hexDigits = elementSize * 2;
      const hexStr = val.toString(16).padStart(hexDigits, '0');
      rowElements.push(`0x${isUpper ? hexStr.toUpperCase() : hexStr.toLowerCase()}`);
    }

    const isLastChunk = i + elementsPerLine * elementSize >= totalLen;
    lines.push(`    ${rowElements.join(', ')}${isLastChunk ? '' : ','}`);
  }

  const footer = `
};
`;

  return header + lines.join('\n') + footer;
}
