import type { ParsedBinary } from '../types';
import { MemoryBuffer } from '../MemoryBuffer';

export function parseCArray(text: string, baseAddress = 0, fileName?: string): ParsedBinary {
  const braceMatch = text.match(/\{([\s\S]*?)\}/);
  const targetText = braceMatch ? braceMatch[1] : text;

  const matches = targetText.match(/0x[0-9a-fA-F]{1,2}|\b[0-9a-fA-F]{2}\b/g) || [];
  const bytes: number[] = [];

  for (const m of matches) {
    const val = parseInt(m.startsWith('0x') || m.startsWith('0X') ? m.substring(2) : m, 16);
    if (!isNaN(val) && val >= 0 && val <= 255) {
      bytes.push(val);
    }
  }

  const segments = [
    {
      startAddress: baseAddress,
      data: new Uint8Array(bytes),
    },
  ];

  const memoryBuffer = new MemoryBuffer(segments);

  return {
    format: 'c_array',
    fileName,
    segments: memoryBuffer.getSegments(),
    minAddress: memoryBuffer.getMinAddress(),
    maxAddress: memoryBuffer.getMaxAddress(),
    totalBytes: memoryBuffer.getTotalBytes(),
    warnings: bytes.length === 0 ? ['No C array byte definitions found inside braces.'] : [],
    errors: [],
  };
}

export function writeCArray(
  memoryBuffer: MemoryBuffer,
  arrayName = 'firmware_data',
  bytesPerLine = 12
): string {
  const { buffer, baseAddress } = memoryBuffer.toContiguousBuffer();
  const totalLen = buffer.length;

  const header = `// Generated by OmniHex Binary Converter
// Size: ${totalLen} bytes (${(totalLen / 1024).toFixed(2)} KB)
// Base Address: 0x${baseAddress.toString(16).padStart(8, '0').toUpperCase()}

#include <stdint.h>

const uint8_t ${arrayName}[${totalLen}] = {
`;

  const lines: string[] = [];
  for (let i = 0; i < totalLen; i += bytesPerLine) {
    const chunk = buffer.subarray(i, i + bytesPerLine);
    const hexArray = Array.from(chunk).map(b => `0x${b.toString(16).padStart(2, '0').toUpperCase()}`);
    const isLastChunk = i + bytesPerLine >= totalLen;
    lines.push(`    ${hexArray.join(', ')}${isLastChunk ? '' : ','}`);
  }

  const footer = `
};
`;

  return header + lines.join('\n') + footer;
}
